In [35]:
import pandas as pd

df_1 = pd.read_csv("df_aistartups.csv")

df_1.head(5)

,company,deal_date,round_type,amount_usd_millions,pre_money_valuation_millions,post_money_valuation_millions,lead_investors,other_investors,sector,subsector,...,ipo_status,key_products,open_source,source,year,quarter,month,deal_size_tier,is_us_company,stage_number
0,DeepMind,2014-01-26,Acquisition,500,NaN,NaN,Google (acquirer),NaN,Foundation Model / Research,AI Research Lab,...,Acquired by Google,"AlphaFold, Gemini, AlphaGo",True,"The Information, Google",2014,1,1,Large ($500M+),False,0
1,OpenAI,2019-07-22,Strategic Investment,1000,NaN,NaN,Microsoft,None disclosed,Foundation Model / LLM,General-Purpose AI,...,Private,"GPT-2, OpenAI Five",True,Microsoft blog,2019,3,7,Unicorn ($1B+),True,8
2,Palantir,2020-09-30,Direct Listing,0,NaN,15800.0,Public Market (NYSE),NaN,AI Application,Data Analytics / Defense AI,...,Public (NYSE: PLTR),"Foundry, Gotham, AIP",False,SEC filing,2020,3,9,Early (<$100M),True,10
3,UiPath,2021-04-21,IPO,1340,NaN,35800.0,Public Market (NYSE),"Morgan Stanley, JPMorgan, BofA",AI Application,Robotic Process Automation,...,Public (NYSE: PATH),"UiPath Platform, AI Center",False,SEC S-1 filing,2021,2,4,Unicorn ($1B+),True,10
4,SenseTime,2021-12-20,IPO,740,NaN,16800.0,Public Market (HKEX),"Cornerstone: CITIC, CICC, HAO Capital",AI Application,Computer Vision / Smart City,...,Public (HKEX: 0020),"SenseCore, facial recognition, autonomous driving",False,HKEX filings,2021,4,12,Large ($500M+),False,10

In [36]:
df_2 = pd.read_csv("df_invest_ai.csv")

df_2.head(5)

,name,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,360pi,|Semantic Web|Artificial Intelligence|Shopping...,Artificial Intelligence,4100000.0,operating,CAN,ON,Ottawa,Ottawa,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,365looks,|Artificial Intelligence|Technology|Fashion|,Fashion,73047.0,operating,ESP,NaN,ESP - Other,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,405Labs,|Machine Learning|Network Security|,Machine Learning,81000.0,operating,USA,CA,San Diego,San Diego,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AdStage,|Sales and Marketing|SEO|Internet|Software|Ent...,Software,8750000.0,operating,USA,CA,SF Bay Area,San Francisco,4.0,...,0.0,0.0,6250000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ADTELLIGENCE,|Customer Service|Reviews and Recommendations|...,Machine Learning,NaN,operating,DEU,NaN,Frankfurt,Mannheim,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
df_2.columns

Index(['name', 'category_list', 'market', 'funding_total_usd', 'status',
       'country_code', 'state_code', 'region', 'city', 'funding_rounds',
       'founded_at', 'founded_month', 'founded_quarter', 'founded_year',
       'first_funding_at', 'last_funding_at', 'seed', 'venture',
       'equity_crowdfunding', 'undisclosed', 'convertible_note',
       'debt_financing', 'angel', 'grant', 'private_equity', 'post_ipo_equity',
       'post_ipo_debt', 'secondary_market', 'product_crowdfunding', 'round_A',
       'round_B', 'round_C', 'round_D', 'round_E', 'round_F', 'round_G',
       'round_H'],
      dtype='str')

In [38]:
df_1.columns

Index(['company', 'deal_date', 'round_type', 'amount_usd_millions',
       'pre_money_valuation_millions', 'post_money_valuation_millions',
       'lead_investors', 'other_investors', 'sector', 'subsector', 'hq_city',
       'hq_country', 'founded_year', 'ceo', 'employees_approx',
       'annual_revenue_millions', 'profitable', 'ipo_status', 'key_products',
       'open_source', 'source', 'year', 'quarter', 'month', 'deal_size_tier',
       'is_us_company', 'stage_number'],
      dtype='str')

In [39]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        38 non-null     str
 1   deal_date                      38 non-null     str
 2   round_type                     38 non-null     str
 3   amount_usd_millions            38 non-null     int64
 4   pre_money_valuation_millions   28 non-null     float64
 5   post_money_valuation_millions  31 non-null     float64
 6   lead_investors                 38 non-null     str
 7   other_investors                36 non-null     str
 8   sector                         38 non-null     str
 9   subsector                      38 non-null     str
 10  hq_city                        38 non-null     str
 11  hq_country                     38 non-null     str
 12  founded_year                   38 non-null     int64
 13  ceo                            38 non-null     str
 14  employees_approx               38 non-null     int64
 15  annual_revenue_millions        25 non-null     float64
 16  profitable                     38 non-null     bool
 17  ipo_status                     38 non-null     str
 18  key_products                   38 non-null     str
 19  open_source                    38 non-null     bool
 20  source                         38 non-null     str
 21  year                           38 non-null     int64
 22  quarter                        38 non-null     int64
 23  month                          38 non-null     int64
 24  deal_size_tier                 38 non-null     str
 25  is_us_company                  38 non-null     bool
 26  stage_number                   38 non-null     int64
dtypes: bool(3), float64(3), int64(7), str(14)
memory usage: 15.8 KB